### ISSUE TITLE
GraphMolWrap.RDKFuncsPINVOKE Exception

### ISSUE THREAD

**Issue by Lumisa-ay** [kazuyaujihara/build-rdkit#1]
when i use this package in my asp.net websit ,the RWMol Class Init   throw  a error message "GraphMolWrap.RDKFuncsPINVOKE”的类型初始值设定项引发异常"  ;but is use this package in Console 
project thats all ok

**Comment by k-ujihara** [comment]
Current implementation assumes unmanaged DLLs are stored under the managed DLL. ASP.NET relocates managed DLL but not unmanaged DLL. So we need to review https://github.com/kazuyaujihara/build-rdkit/blob/master/csharp_wrapper/RDKFuncsPINVOKE_Loader.cs to fix this problem.

**Comment by Lumisa-ay** [comment]
thanks, I copy  all dll in  X64(my server is  x64)  folder to asp.net bin folder same server can run well

**Comment by k-ujihara** [comment]
Oh, that's a good news. 
Thanks for your comments.
