### ISSUE TITLE
PINVOKE error on linux

### ISSUE THREAD

**Issue by bitstormFA** [kazuyaujihara/build-rdkit#3]
Hi,

This is a great package as I was looking forward to have a way to use rdkit from f#!

I did run tests on windows and everything worked as expected but I didn't manage to get anything working on linux.
I tried Arch linux and Redhat 8.3.1 but with my first attempt to use MolFromSmiles I already get

`
System.TypeInitializationException: The type initializer for 'GraphMolWrap.RDKFuncsPINVOKE' threw an exception.
 ---> System.TypeInitializationException: The type initializer for 'SWIGExceptionHelper' threw an exception.
 ---> System.DllNotFoundException: Unable to load shared library 'RDKFuncs' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libRDKFuncs: cannot open shared object file: No such file or directory
   at GraphMolWrap.RDKFuncsPINVOKE.SWIGExceptionHelper.SWIGRegisterExceptionCallbacks_RDKFuncs(ExceptionDelegate applicationDelegate, ExceptionDelegate arithmeticDelegate, ExceptionDelegate divideByZeroDelegate, ExceptionDelegate indexOutOfRangeDelegate, ExceptionDelegate invalidCastDelegate, ExceptionDelegate invalidOperationDelegate, ExceptionDelegate ioDelegate, ExceptionDelegate nullReferenceDelegate, ExceptionDelegate outOfMemoryDelegate, ExceptionDelegate overflowDelegate, ExceptionDelegate systemExceptionDelegate)
   at GraphMolWrap.RDKFuncsPINVOKE.SWIGExceptionHelper..cctor()
   --- End of inner exception stack trace ---
   at GraphMolWrap.RDKFuncsPINVOKE.SWIGExceptionHelper..ctor()
   at GraphMolWrap.RDKFuncsPINVOKE..cctor()
   --- End of inner exception stack trace ---
   at GraphMolWrap.RDKFuncsPINVOKE.RWMol_MolFromSmiles__SWIG_3(String jarg1)
   at GraphMolWrap.RWMol.MolFromSmiles(String smi)
   at <StartupCode$FSI_0005>.$FSI_0005.main@()
`

The code to reproduce is
`
#r "nuget: RDKit.DotNetWrap, 0.2020094.1"

open GraphMolWrap

let mol = RWMol.MolFromSmiles "CS(=O)(=O)NC1C([NH3+])C1O"
`

The environment is a dotnet interactive notebook in VSCode running dotnet sdk 5.0.103.
I am new to this programming environment so please let me know if you need further information.
The error is the same with Arch linux and Redhat 8.3.1.

**Comment by k-ujihara** [comment]
You are right. Making links for `so` files is required and 
- libboost 1.71.0
- libcairo2-dev
- libfreetype6
- liblng16-dev

are also required to install.

```bash
ln -s libRDKitAbbreviations.so.1.2020.09.4 libRDKitAbbreviations.so.1
ln -s libRDKitAlignment.so.1.2020.09.4 libRDKitAlignment.so.1
ln -s libRDKitAvalonLib.so.1.2020.09.4 libRDKitAvalonLib.so.1
ln -s libRDKitCatalogs.so.1.2020.09.4 libRDKitCatalogs.so.1
ln -s libRDKitChemReactions.so.1.2020.09.4 libRDKitChemReactions.so.1
ln -s libRDKitChemTransforms.so.1.2020.09.4 libRDKitChemTransforms.so.1
ln -s libRDKitDataStructs.so.1.2020.09.4 libRDKitDataStructs.so.1
ln -s libRDKitDepictor.so.1.2020.09.4 libRDKitDepictor.so.1
ln -s libRDKitDescriptors.so.1.2020.09.4 libRDKitDescriptors.so.1
ln -s libRDKitDistGeomHelpers.so.1.2020.09.4 libRDKitDistGeomHelpers.so.1
ln -s libRDKitDistGeometry.so.1.2020.09.4 libRDKitDistGeometry.so.1
ln -s libRDKitEigenSolvers.so.1.2020.09.4 libRDKitEigenSolvers.so.1
ln -s libRDKitFMCS.so.1.2020.09.4 libRDKitFMCS.so.1
ln -s libRDKitFileParsers.so.1.2020.09.4 libRDKitFileParsers.so.1
ln -s libRDKitFilterCatalog.so.1.2020.09.4 libRDKitFilterCatalog.so.1
ln -s libRDKitFingerprints.so.1.2020.09.4 libRDKitFingerprints.so.1
ln -s libRDKitForceField.so.1.2020.09.4 libRDKitForceField.so.1
ln -s libRDKitForceFieldHelpers.so.1.2020.09.4 libRDKitForceFieldHelpers.so.1
ln -s libRDKitGraphMol.so.1.2020.09.4 libRDKitGraphMol.so.1
ln -s libRDKitInchi.so.1.2020.09.4 libRDKitInchi.so.1
ln -s libRDKitMolAlign.so.1.2020.09.4 libRDKitMolAlign.so.1
ln -s libRDKitMolDraw2D.so.1.2020.09.4 libRDKitMolDraw2D.so.1
ln -s libRDKitMolEnumerator.so.1.2020.09.4 libRDKitMolEnumerator.so.1
ln -s libRDKitMolHash.so.1.2020.09.4 libRDKitMolHash.so.1
ln -s libRDKitMolStandardize.so.1.2020.09.4 libRDKitMolStandardize.so.1
ln -s libRDKitMolTransforms.so.1.2020.09.4 libRDKitMolTransforms.so.1
ln -s libRDKitO3AAlign.so.1.2020.09.4 libRDKitO3AAlign.so.1
ln -s libRDKitOptimizer.so.1.2020.09.4 libRDKitOptimizer.so.1
ln -s libRDKitPartialCharges.so.1.2020.09.4 libRDKitPartialCharges.so.1
ln -s libRDKitRDGeneral.so.1.2020.09.4 libRDKitRDGeneral.so.1
ln -s libRDKitRDGeometryLib.so.1.2020.09.4 libRDKitRDGeometryLib.so.1
ln -s libRDKitRDInchiLib.so.1.2020.09.4 libRDKitRDInchiLib.so.1
ln -s libRDKitRDStreams.so.1.2020.09.4 libRDKitRDStreams.so.1
ln -s libRDKitRGroupDecomposition.so.1.2020.09.4 libRDKitRGroupDecomposition.so.1
ln -s libRDKitRingDecomposerLib.so.1.2020.09.4 libRDKitRingDecomposerLib.so.1
ln -s libRDKitScaffoldNetwork.so.1.2020.09.4 libRDKitScaffoldNetwork.so.1
ln -s libRDKitSimDivPickers.so.1.2020.09.4 libRDKitSimDivPickers.so.1
ln -s libRDKitSmilesParse.so.1.2020.09.4 libRDKitSmilesParse.so.1
ln -s libRDKitSubgraphs.so.1.2020.09.4 libRDKitSubgraphs.so.1
ln -s libRDKitSubstructLibrary.so.1.2020.09.4 libRDKitSubstructLibrary.so.1
ln -s libRDKitSubstructMatch.so.1.2020.09.4 libRDKitSubstructMatch.so.1
ln -s libRDKitTautomerQuery.so.1.2020.09.4 libRDKitTautomerQuery.so.1
ln -s libRDKitTrajectory.so.1.2020.09.4 libRDKitTrajectory.so.1
ln -s libRDKitavalon_clib.so.1.2020.09.4 libRDKitavalon_clib.so.1
ln -s libRDKitcoordgen.so.1.2020.09.4 libRDKitcoordgen.so.1
ln -s libRDKithc.so.1.2020.09.4 libRDKithc.so.1
ln -s libRDKitmaeparser.so.1.2020.09.4 libRDKitmaeparser.so.1
```

**Comment by bitstormFA** [comment]
Many thanks for your help! 
I will make sure I have the dependencies installed, create the links and give it a try.

**Comment by k-ujihara** [comment]
Dear @bitstormGER ,
I fixed it and uploaded NuGet package at https://www.nuget.org/packages/RDKit.DotNetWrap/0.2020094.2.  But still now, it requires set `LD_LIBRARY_PATH`.
See https://github.com/kazuyaujihara/build-rdkit/tree/develop/myApp.

**Comment by bitstormFA** [comment]
Excellent - many thanks!
