### ISSUE TITLE
Unable to load DLL 'RDKFuncs' after publishing solution

### ISSUE THREAD

**Issue by john1martel** [kazuyaujihara/build-rdkit#4]
Hello,

I am using Visual Studio 2019 for VSTO Office add-in with .NET framework 4.7.2 (windows 10 and Office 365 64-bit. I installed the Nuget package fine, and the solution compiles and runs fine in debug mode. However after publishing the solution, I get unable to load DLL 'RDKFuncs'  at runtime. I have checked the References in Visual Studio and it's howing Copy Local as true. I am not sure what I am missing.

**Comment by k-ujihara** [comment]
You need to place all DLLs in the sane directory. Refer NCDK-Excel, which is VSTO application and uses RDkitDotNetWrap. 
https://github.com/kazuyaujihara/NCDK-Excel

**Comment by john1martel** [comment]
Thanks it's working now. Oddly when you create a .NET Core solution, you dont have this problem when publishing the solution.
