### ISSUE TITLE
example code to calculate moleclar descriptors

### ISSUE THREAD

**Issue by drjahu** [kazuyaujihara/build-rdkit#7]
Hello!
I try to calculate all molecular descriptors but seem not to find the correct examples. Would it be possible for you to provide some example code on how to calculate molecular Graph Descriptors (BalabanJ, Chi0, Kappa1,...), Descriptors (EState_VSA10,...), or Fragments(fr_Al_COO,...) using the `RDKit.DotNetWrap `package?

Thank you so much for your time and effort!
Looking forward for a short reply!
Jan

**Comment by k-ujihara** [comment]
Sorry for delay reply.
Example code for BalabanJ, Chi0, Kappa1 is below. 
```csharp
var mol = RWMol.MolFromSmiles("O=Cc1ccc(O)c(OC)c1 COc1cc(C=O)ccc1O");
Console.WriteLine(RDKFuncs.computeBalabanJ(mol));
Console.WriteLine(RDKFuncs.calcChi0n(mol));
Console.WriteLine(RDKFuncs.calcKappa1(mol));
```

The features implemented using Python including EState_VSA10 are not contained. See https://github.com/rdkit/rdkit/blob/master/rdkit/Chem/EState/EState_VSA.py. 
We need to migrate python to C#.
